version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastify_app
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    depends_on:
      - db
    working_dir: /app
